version: '3'
services:
  agent:
    image: "datadog/agent:latest"
    container_name: "datadog-agent"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_HOSTNAME=datadog-workshop
      # Add DD_APM_ANALYZED_SPANS to the Agent container environment.
      # Compatible with version 12.6.5250 or above.
      - DD_APM_ANALYZED_SPANS=users-api|express.request=1,sensors-api|flask.request=1,pumps-service|flask.request=1,iot-frontend|flask.request=1
      - DD_TAGS='env:workshop'
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_AC_EXCLUDE='image:agent'
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro

    labels:
      com.datadoghq.ad.logs: '[{"source": "docker", "service": "agent"}]'

  frontend:
    container_name: "frontend"
    environment:
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
    build: .
    command: flask run --port=5000 --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - "./frontend:/app"
    depends_on:
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "frontend", "service": "frontend", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_ip", "pattern" : "(172.20.0.1|Traceback)"}]}]'

  noder:
    container_name: "noder"
    build: ./node-api
    command: nodemon server.js
    ports:
      - "5004:5004"
    volumes:
      - "./node-api:/app"
      - /app/node_modules
    depends_on:
      - frontend
      - redis
    environment:
      - DD_ENV=workshop
    labels:
      com.datadoghq.ad.logs: '[{"source": "noder", "service": "noder"}]'
      
  pumps:
    container_name: "pumps"
    environment:
      - FLASK_APP=thing.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    build: ./iot-devices
    command: flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    volumes:
      - "./iot-devices:/app"
    depends_on:
      - frontend
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "pumps-service", "service": "pumps-service"}]'

  redis:
    container_name: "redis"
    image: redis:latest
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'

  sensors:
    container_name: "sensors"
    environment:
      - FLASK_APP=sensors.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    build: ./sensors
    command: flask run --port=5002 --host=0.0.0.0
    ports:
      - "5002:5002"
    volumes:
      - "./sensors:/app"
    depends_on:
      - frontend
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "sensors", "service": "sensors-api"}]'

  db:
    container_name: "postgres"
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - 5432:5432
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "postgres", "service": "postgres"}]'

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "adminer", "service": "adminer"}]'
